OBJECTS=array.o boolean.o config.o control.o dictionary.o file.o\
	integer.o main.o math.o misc.o name.o operator.o\
	poly.o property.o real.o save.o stack.o string.o unix.o
#LIBS=libww.a -lsuntool -lsunwindow -lpixrect
# no ww support
LIBS= -lpixrect
XLIB=/usr/lib/libX11.a
GRAPHICS=cache.o colour.o device.o fill.o font.o gsave.o image.o mat.o matrix.o\
	pat.o path.o state.o stroke.o
  
SOURCES=array.c boolean.c config.c control.c dictionary.c file.c\
	integer.c main.c math.c misc.c name.c operator.c\
	poly.c property.c real.c save.c stack.c string.c unix.c\
	cache.c colour.c device.c fill.c font.c gsave.c image.c mat.c matrix.c\
	pat.c path.c state.c stroke.c
LINT=lint
LFLAGS= -lm

GCCDIR=/h/xwindows/gcc-1.33
GCC=$(GCCDIR)/gcc -B$(GCCDIR)/ -traditional
CC=$(GCC)
CFLAGS=-O -g
#CFLAGS=-O -fsingle
#CFLAGS=-p


default: xps

PS:	$(OBJECTS) $(GRAPHICS) hard.o canon.a
	$(CC) $(CFLAGS)  $(OBJECTS) $(GRAPHICS) hard.o canon.a -lm ${LIBS} -o PS

sunPS:	$(OBJECTS) $(GRAPHICS) hard.o canon.a pixrect
	$(CC) $(CFLAGS)  $(OBJECTS) $(GRAPHICS) hard.o canon.a -lm -lpixrect -o sunPS

CPS:	$(OBJECTS) $(GRAPHICS) colour-ww.o trapezoid.o canon.o
	$(CC) $(CFLAGS)  $(OBJECTS) $(GRAPHICS) colour-ww.o canon.o trapezoid.o -lm `libs` -o CPS

postscript:	$(OBJECTS) $(GRAPHICS) adapter.o protocol.o
	$(CC) $(CFLAGS) $(OBJECTS) $(GRAPHICS) adapter.o protocol.o -lm -o postscript

xps: $(OBJECTS) $(GRAPHICS) X11.o canon.a $(XLIB)
	rm -f xps
	$(CC) -o xps $(CFLAGS) $(OBJECTS) $(GRAPHICS) X11.o canon.a -lm $(XLIB)

#x10ps:	$(OBJECTS) $(GRAPHICS) X.o
#	$(CC) $(CFLAGS)  $(OBJECTS) $(GRAPHICS) X.o -lm -lX10 -o x10ps

#x11ps: $(OBJECTS) $(GRAPHICS) X11.o canon.a
#	$(CC) -o x11ps $(OBJECTS) $(GRAPHICS) X11.o canon.a -lm -lX11

canon.a:	canon.o screen.o trapezoid.o paint.o
	ar ruv canon.a canon.o screen.o trapezoid.o paint.o
	ranlib canon.a

lint:
	$(LINT) $(LFLAGS) $(SOURCES) $(LINTFILTER)

viewer:	protocol.o viewer.o hard.o canon.a
	$(CC) protocol.o viewer.o hard.o canon.a ${LIBS} -o viewer

xviewer: protocol.o viewer.o X.o nullX.o
	$(CC) protocol.o viewer.o X.o nullX.o -lX10 -o xviewer

all:	PS postscript viewer

ww:	ww.o wwlib installww

sun:	ww wwsun

orion:	orion.o installorion orionlib

X.o:	
	${CC} ${CFLAGS} -c -I/usr/include/X10 X.c

wwlib:
	if [ -f libww.a ]; \
	then \
		echo 'echo libww.a' >lww; \
	else \
		echo 'echo -lww' >lww; \
	fi; \
	chmod +x lww
	echo "echo `lww`" >libs; chmod +x libs

wwsun:	
	echo "echo `lww` -lsuntool -lsunwindow -lpixrect" >libs; chmod +x libs

orionlib:
	echo 'echo -lG' >libs; chmod +x libs

installww:
	cp ww.o hard.o

installorion:
	cp orion.o hard.o

install : xps
	install -s -m 755 xps /local/bin/X11/xps
	rm -f /local/bin/postscript
	ln -s /local/bin/X11/xps /local/bin/postscript
	install -c -m 444 ../doc/xps.l /local/man/man1/xps.1
# Yuk!
	@echo 'install ../postscript by hand in /local/share if anything is changed'

clean:
	rm -f *.o make.out xps x10ps x11ps sunPS postscript CPS canon.a \
		xviewer viewer ww sun orion
